#pragma once

#include "../../interfaces/IOptimizer.h"

// Simulated Annealing optimiser.
//
// At each iteration a neighbour is generated by perturbing a random subset of
// the current solution. The neighbour is accepted unconditionally if it
// improves cost; otherwise it is accepted with Boltzmann probability
// exp(-delta / T), allowing escape from local minima.
//
// Temperature follows a geometric cooling schedule: T_k = T_0 * alpha^k.
// As T -> 0 the algorithm converges to greedy hill-climbing.
class SimulatedAnnealing : public IOptimizer {
public:
    SimulatedAnnealing(int    max_iterations     = 5000,
                       double initial_temp       = 5.0,
                       double cooling_rate       = 0.995,
                       double perturbation_scale = 1.0,
                       unsigned int seed         = 42);

    OptimizationResult optimize(IProblem& problem) override;

private:
    int          m_max_iterations;
    double       m_initial_temp;
    double       m_cooling_rate;
    double       m_perturbation_scale;
    unsigned int m_seed;
};
